"""Add meter_readings table

Revision ID: 8e056f7426ee
Revises: cbccbd45f59b
Create Date: 2026-03-30 10:38:57.249235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e056f7426ee'
down_revision: Union[str, None] = 'cbccbd45f59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('previous_reading', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_reading', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumption', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    # ### end Alembic commands ###
