"""Sync models with database

Revision ID: d5a61d0380e5
Revises: 9463da0b1201
Create Date: 2026-04-10 12:09:09.248154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a61d0380e5'
down_revision: Union[str, None] = '9463da0b1201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.add_column('maintenance_requests', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('maintenance_requests', sa.Column('landlord_deduction', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('agreement_document_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'agreement_document_url')
    op.drop_column('tenants', 'is_active')
    op.drop_column('maintenance_requests', 'landlord_deduction')
    op.drop_column('maintenance_requests', 'cost')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
